AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal Proton Environment Template

Resources:
  DummyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/proton/demo-env-${AWS::StackName}
      RetentionInDays: 1
