schema:
  format:
    openapi: "3.0.0"
  properties:
    service_instance_name:
      type: string
    team:
      type: string
      default: platform
    version:
      type: string
      default: v1
  required:
    - service_instance_name