AWSTemplateFormatVersion: '2010-09-09'
Description: Dummy Proton Service Template for GitOps Serverless Demo

Resources:
  DummyWait:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  ServiceId:
    Description: Dummy output
    Value: !Ref DummyWait